# Generated by Django 4.0.8 on 2022-12-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import problems.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='example',
            field=models.ForeignKey(blank=True, limit_choices_to={'open_solution': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.problem', verbose_name='Пример'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problemtype',
            field=models.ForeignKey(blank=True, default=problems.models.ProblemType.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='problems.problemtype', verbose_name='Тип задания'),
        ),
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.ForeignKey(default=problems.models.Source.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='source', to='problems.source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='problems.branch', verbose_name='Родительская категория'),
        ),
    ]
