# Generated by Django 4.0.8 on 2022-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('item_number', models.IntegerField(default=None, null=True, verbose_name='Порядковый номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_multi_item', models.BooleanField(default=False, verbose_name='Мульти элемент')),
                ('is_child', models.BooleanField(default=False, verbose_name='Подзадание')),
                ('child_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Порядковый номер подзадания')),
            ],
            options={
                'verbose_name': 'Элемент Списка',
                'verbose_name_plural': 'Элементы Списков',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('not_published', 'Не опубликовано')], default='not_published', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Список заданий',
                'verbose_name_plural': 'Списки заданий',
            },
        ),
        migrations.CreateModel(
            name='MultiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100, verbose_name='Условие')),
                ('columns', models.IntegerField(default=1, verbose_name='Кол-во колонок')),
            ],
            options={
                'verbose_name': 'Мульти элемент списка',
                'verbose_name_plural': 'Мульти элементы списков',
            },
        ),
    ]
