# Generated by Django 4.0.2 on 2022-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_exercise_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='html_field',
            field=models.TextField(default='', editable=False),
        ),
    ]
