# Generated by Django 4.0.2 on 2022-02-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_exercise_time_created_exercise_time_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Раздел')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='area',
        ),
        migrations.AddField(
            model_name='exercise',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.branch'),
        ),
    ]
