# Generated by Django 4.0.2 on 2022-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_branch_remove_exercise_area_exercise_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(default='', verbose_name='Метка'),
        ),
    ]
