# Generated by Django 4.0.2 on 2022-02-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_theme_exercise_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='branch',
        ),
        migrations.AddField(
            model_name='theme',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.branch'),
        ),
    ]
