# Generated by Django 4.0.2 on 2022-02-26 16:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_rename_exercise_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branch',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='problems.branch', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='branch',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='theme',
            name='level',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='tree_id',
        ),
    ]
