# Generated by Django 4.0.2 on 2022-03-02 09:38

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_rename_name_branch_title_alter_theme_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='theme',
        ),
        migrations.AddField(
            model_name='problem',
            name='branch',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.branch', verbose_name='Раздел'),
        ),
    ]
