# Generated by Django 4.0.2 on 2022-03-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_remove_problem_theme_problem_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.TextField(max_length=50, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='problem',
            name='complexity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(null=True, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.source'),
        ),
    ]
