# Generated by Django 4.0.2 on 2022-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_source_problem_answer_problem_complexity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='complexity',
            field=models.IntegerField(null=True, verbose_name='Сложность'),
        ),
    ]
