# Generated by Django 4.0.2 on 2022-03-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_alter_problem_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
