# Generated by Django 4.0.3 on 2022-03-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_author_problem_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='html_field',
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='complexity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.source', verbose_name='Источник'),
        ),
    ]
