# Generated by Django 4.0.3 on 2022-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_remove_problem_html_field_alter_problem_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Списки задач',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='lists',
            field=models.ManyToManyField(to='problems.list'),
        ),
    ]
