# Generated by Django 4.0.3 on 2022-03-04 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_list_problem_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='problems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
    ]
