# Generated by Django 4.0.3 on 2022-03-04 12:53

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_remove_problem_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Элемент Списка',
                'verbose_name_plural': 'Элементы Списка',
            },
        ),
        migrations.AlterField(
            model_name='list',
            name='problems',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.list'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
    ]
