# Generated by Django 4.0.3 on 2022-03-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_listitem_alter_list_problems_delete_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='problems',
        ),
    ]
