# Generated by Django 4.0.3 on 2022-03-05 10:12

from django.db import migrations
import django.db.models.deletion
import mptt.fields
import problems.models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_remove_list_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='branch',
            field=mptt.fields.TreeForeignKey(default=problems.models.Branch.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='problems.branch', verbose_name='Раздел'),
        ),
    ]
