# Generated by Django 4.0.3 on 2022-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_alter_problem_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='time_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('not_published', 'Не опубликовано')], default='not_published', max_length=15, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('not_published', 'Не опубликовано')], default='not_published', max_length=15, verbose_name='Статус'),
        ),
    ]
