# Generated by Django 4.0.8 on 2022-11-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='child_number',
            field=models.IntegerField(default=None, null=True, verbose_name='Порядковый номер подзадания'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_child',
            field=models.BooleanField(default=False, verbose_name='Подзадание'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_multi_item',
            field=models.BooleanField(default=False, verbose_name='Мульти элемент'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.IntegerField(default=None, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='item',
            name='multi_items',
            field=models.ManyToManyField(blank=True, related_name='multiitems', to='listmanager.multiitem', verbose_name='Массив мульти элементов'),
        ),
    ]
