# Generated by Django 4.0.8 on 2022-11-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmanager', '0002_item_child_number_item_is_active_item_is_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='child_number',
            field=models.IntegerField(blank=True, default=None, verbose_name='Порядковый номер подзадания'),
        ),
    ]
