# Generated by Django 4.0.8 on 2022-11-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmanager', '0003_alter_item_child_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='child_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Порядковый номер подзадания'),
        ),
    ]
