# Generated by Django 4.0.8 on 2022-11-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listmanager', '0005_remove_item_multi_items_item_multi_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='multi_items',
            field=models.ForeignKey(blank=True, default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, related_name='multiitems', to='listmanager.multiitem', verbose_name='В мультемассиве'),
        ),
    ]
