# Generated by Django 4.0.8 on 2022-11-19 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('body', models.TextField(blank=True, verbose_name='Содержание')),
                ('is_true', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Определение',
                'verbose_name_plural': 'Определения',
            },
        ),
        migrations.CreateModel(
            name='Theorem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('body', models.TextField(blank=True, verbose_name='Содержание')),
                ('is_true', models.BooleanField(default=True)),
                ('reverse_is_true', models.BooleanField(default=None)),
                ('proof', models.TextField(blank=True)),
                ('reverse_theorem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.theorem')),
            ],
            options={
                'verbose_name': 'Теорема',
                'verbose_name_plural': 'Теоремы',
            },
        ),
    ]
